### ISSUE TITLE
Node clone functionality so secondary bgimages can be created

### ISSUE THREAD

**Issue by edutrul** [bugguide/bugguide#44]
clone module in use; see BUGG-5.

This module has an omit setting. Need to omit node types other than bgimage.

Permission to clone own nodes only need to be enforced.

### Comments

John:
Variables created after submitting node clone configuration page (saved via system_settings_form):

```
clone_method: prepopulate
clone_nodes_without_confirm: '0'
clone_menu_links: '0'
clone_use_node_type_name: 0
clone_reset_bgref: 0
clone_reset_book_reference: 0
clone_reset_forum: 0
clone_reset_bgpage: 0
clone_reset_bgimage: 0
clone_reset_bglink: 0
clone_reset_page: 0
clone_reset_story: 0
clone_omitted:
  bgref: bgref
  book_reference: book_reference
  forum: forum
  bgpage: bgpage
  bglink: bglink
  page: page
  story: story
  bgimage: 0
```

Juampy:
What's left here to do? Clone is working isn't it?
